## 各種機能の有効化・無効化設定
## JoinMessage...参加時にプレイヤーにメッセージを送信
EnableJoinMessage: true
## JoinTitle...参加時にプレイヤーにタイトルを表示
EnableJoinTitle: true
## JoinSound...参加時にレベルアップした時の音を鳴らす
EnableJoinSound: true
## CustomJoinMessage...プレイヤーの参加メッセージをアレンジする
EnableCustomJoinMessage: true
## CustomQuitMessage...プレイヤーが退室した時のメッセージをアレンジする
EnableCustomQuitMessage: true

## 各種機能の詳細設定
## JoinMessage...送信するメッセージの内容を設定
JoinMessage:
  - §7======= Welcome! =======
  - §7CoSSeへようこそ！
  - §7ワールド移動などはしふぉんでどうぞ
  - §7https://info.comorevi.net
  - §7======================
## JoinTitle...送信するタイトルの内容
JoinTitle: §cC§fo§cSS§fe - §a生活§f鯖
## JoinSubTitle...送信するタイトルのサブタイトルの内容
JoinSubTitle: §7for MinecraftBE 1.14.x
## CustomJoinMessage...参加メッセージのカスタマイズ({username}はユーザーの名前が入ります)
CustomJoinMessage: "§7{username}が参加しました！待ってました！！( ͡° ͜ʖ ͡°)"
## CustomQuitMessage...退出メッセージのカスタマイズ({username}はユーザーの名前が入ります)
CustomQuitMessage: "§7{username}が退出しました。良い１日を！！"